sudo: false
language: php

cache:
  directories:
  - $HOME/.composer/cache
  - vendor

matrix:
  fast_finish: true
  include:
  - php: 5.6
  - php: 7

before_install:
- openssl aes-256-cbc -K $encrypted_d3e7229d64cc_key -iv $encrypted_d3e7229d64cc_iv
   -in .travis/secrets.tar.enc -out .travis/secrets.tar -d
- composer self-update

install:
- travis_retry composer install --no-interaction
- composer info -i

script:
- composer test
